//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolioAspNetMvc5.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        public int ContactID { get; set; }
        public string NameSurname { get; set; }
        public string Mail { get; set; }
        public string Title { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
    }
}
